CREATE TABLE sales (
    row_id INT PRIMARY KEY,
    order_priority VARCHAR(50),
    discount DECIMAL(5,2),
    unit_price DECIMAL(10,2),
    shipping_cost DECIMAL(10,2),
    customer_id INT,
    customer_name VARCHAR(100),
    ship_mode VARCHAR(50),
    customer_segment VARCHAR(50),
    product_category VARCHAR(50),
    product_sub_category VARCHAR(50),
    product_container VARCHAR(50),
    product_name VARCHAR(255),
    product_base_margin DECIMAL(5,2),
    region VARCHAR(50),
    manager VARCHAR(100),
    state_or_province VARCHAR(50),
    city VARCHAR(100),
    postal_code VARCHAR(20),
    order_date DATE,
    ship_date DATE,
    profit DECIMAL(10,2),
    quantity_ordered INT,
    sales DECIMAL(10,2),
    order_id INT,
    return_status VARCHAR(50)
);
